---
pipeline:
  build:
    image: node:10
    commands:
      - npm install

  test:
    image: node:10
    commands:
      - npm run test:unit

  lint:
    image: node:10
    commands:
      - npm run lint
