version: 2
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
  enable-javascript: true
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
  concurrency: 50
static:
  cleanUrls: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
