version: 2
discovery:
  concurrency: 16
  launch-options:
    timeout: 90000
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
  enable-javascript: false
  percy-css: |
    #intercom-container {
      display: none;
    }
static:
  include: "**/*.html"
  exclude: ["/includes/**", "/reference/**"]
  options:
    - include: "**/*.html"
      waitForTimeout: 2000
      waitForSelector: body
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
