
# First group
[[toc]]
label = "Get Started"
group = true
[[toc.items]]
label = "Create Account"
url = "/create-account"
items = "./source/whatever/toc.toml"
[[toc.items]]
label = "Deploy a Free Cluster"
url = "/deploy-cluster"
[[toc.items]]
label = "Manage Database Users"
url = "/manage-users"
[[toc.items]]
label = "Manage the IP Access List"
url = "/access-list"
[[toc.items]]
label = "Connect to the Cluster"
url = "/connect-to-the-cluster"
[[toc.items]]
label = "Insert and View a Document"
url = "/insert-and-view"
[[toc.items]]
label = "Load Sample Data"
url = "/load-data"
[[toc.items]]
label = "Generate Synthetic Data"
url = "/generate-data"

# second group
[[toc]]
label = "Application Development"
group = true
collapsible = true
[[toc.items]]
label = "Connect to Clusters"
collapsible = true
[[toc.items.items]]
label = "Nested under 'Connect to Clusters'"
url = "/some-nested-element"


# toc : [ { items: [ { label: 'blah' }], label: 'blah' }  ]


# toc : [ { getSta: [ { label: 'blah' }], label: 'blah' }, { ApplicationDevelopment: [ { label: 'blah' }], label: 'blah' }  ]
