from .nodes import Node
from typing import Dict, List, Tuple


class BaseConstructor:
    def construct_mapping(self, node: Node, deep: bool=False) -> Dict: ...
    def construct_pairs(self, node: Node) -> List[Tuple[str, object]]: ...
    def get_single_data(self) -> Dict: ...
    def get_data(self) -> Dict: ...


class SafeConstructor(BaseConstructor): ...


class Constructor(SafeConstructor): ...
