import docutils.nodes
import docutils.frontend


def new_document(path: str, settings: docutils.frontend.Values) -> docutils.nodes.document: ...


class Reporter:
    DEBUG_LEVEL: int = ...
    INFO_LEVEL: int = ...
    WARNING_LEVEL: int = ...
    ERROR_LEVEL: int = ...
    SEVERE_LEVEL: int = ...
