# First group
[[toc]]
label = "This is a 2nd group"
group = true
[[toc.items]]
label = "Connect to the Cluster"
url = "/connect-to-the-cluster"
[[toc.items]]
label = "Insert and View a Document"
url = "/insert-and-view"
[[toc.items]]
label = "Load Sample Data"
url = "/load-data"
[[toc.items]]
label = "Generate Synthetic Data"
url = "/generate-data"