# static left pane
[[toc]]
label = "Get Started"
url = "/get-started"
items = "/get-started-toc.toml"
isTab = true

[[toc]]
label = "Application Development"
url = "/application-development"
items = "/application-development-toc.toml"
isTab = true

# [[toc.items]]

# [[toc.items]]
