from typing import Any, Dict


class Collection:
    def delete_one(self, filter: Dict[str, Any]) -> Any: ...
    def insert_one(self, doc: Dict[str, Any]) -> Any: ...
    def replace_one(self, filter: Dict[str, Any], doc: Dict[str, Any], upsert: bool=False) -> Any: ...
