export const componentMap = async (directives = []) => {
  const imports = {
    admonition: await import('../../../../src/components/Admonition'),
    banner: await import('../../../../src/components/Banner/Banner'),
    blockquote: await import('../../../../src/components/BlockQuote'),
    button: await import('../../../../src/components/Button'),
    card: await import('../../../../src/components/Card'),
    'card-group': await import('../../../../src/components/Card/CardGroup'),
    chapter: await import('../../../../src/components/Chapters/Chapter'),
    chapters: await import('../../../../src/components/Chapters'),
    chatbot: await import('../../../../src/components/ChatbotUi'),
    code: await import('../../../../src/components/Code/Code'),
    'io-code-block': await import('../../../../src/components/Code/CodeIO'),
    cond: await import('../../../../src/components/Cond'),
    container: await import('../../../../src/components/Container'),
    cta: await import('../../../../src/components/CTA'),
    'cta-banner': await import('../../../../src/components/Banner/CTABanner'),
    definitionList: await import('../../../../src/components/DefinitionList'),
    definitionListItem: await import('../../../../src/components/DefinitionList/DefinitionListItem'),
    deprecated: await import('../../../../src/components/VersionModified'),
    'deprecated-version-selector': await import('../../../../src/components/DeprecatedVersionSelector'),
    describe: await import('../../../../src/components/Describe'),
    emphasis: await import('../../../../src/components/Emphasis'),
    extract: await import('../../../../src/components/Extract'),
    field: await import('../../../../src/components/FieldList/Field'),
    field_list: await import('../../../../src/components/FieldList'),
    figure: await import('../../../../src/components/Figure'),
    footnote: await import('../../../../src/components/Footnote'),
    footnote_reference: await import('../../../../src/components/Footnote/FootnoteReference'),
    glossary: await import('../../../../src/components/Glossary'),
    'guide-next': await import('../../../../src/components/GuideNext'),
    heading: await import('../../../../src/components/Heading'),
    hlist: await import('../../../../src/components/HorizontalList'),
    image: await import('../../../../src/components/Image'),
    include: await import('../../../../src/components/Include'),
    introduction: await import('../../../../src/components/Introduction'),
    kicker: await import('../../../../src/components/Kicker'),
    'landing:explore': await import('../../../../src/components/Landing/Explore'),
    'landing:more-ways': await import('../../../../src/components/Landing/MoreWays'),
    'landing:client-libraries': await import('../../../../src/components/StandaloneHeader'),
    'landing:introduction': await import('../../../../src/components/LandingIntro'),
    'landing:product': await import('../../../../src/components/Products/ProductItem'),
    'landing:products': await import('../../../../src/components/Products'),
    line: await import('../../../../src/components/LineBlock/Line'),
    line_block: await import('../../../../src/components/LineBlock'),
    list: await import('../../../../src/components/List'),
    listItem: await import('../../../../src/components/List/ListItem'),
    'list-table': await import('../../../../src/components/ListTable'),
    literal: await import('../../../../src/components/Literal'),
    literal_block: await import('../../../../src/components/LiteralBlock'),
    literalinclude: await import('../../../../src/components/LiteralInclude'),
    only: await import('../../../../src/components/Cond'),
    'openapi-changelog': await import('../../../../src/components/OpenAPIChangelog'),
    paragraph: await import('../../../../src/components/Paragraph'),
    procedure: await import('../../../../src/components/Procedure'),
    ref_role: await import('../../../../src/components/RefRole'),
    reference: await import('../../../../src/components/Reference'),
    release_specification: await import('../../../../src/components/ReleaseSpecification'),
    root: await import('../../../../src/components/Root'),
    rubric: await import('../../../../src/components/Rubric'),
    'search-results': await import('../../../../src/components/SearchResults'),
    section: await import('../../../../src/components/Section'),
    sharedinclude: await import('../../../../src/components/Include'),
    strong: await import('../../../../src/components/Strong'),
    substitution_reference: await import('../../../../src/components/SubstitutionReference'),
    tabs: await import('../../../../src/components/Tabs'),
    target: await import('../../../../src/components/Target'),
    text: await import('../../../../src/components/Text'),
    time: await import('../../../../src/components/Time'),
    title_reference: await import('../../../../src/components/TitleReference'),
    topic: await import('../../../../src/components/Topic'),
    transition: await import('../../../../src/components/Transition'),
    versionadded: await import('../../../../src/components/VersionModified'),
    versionchanged: await import('../../../../src/components/VersionModified'),
  };

  const filteredComponents = directives
    .filter((key) => key in imports)
    .reduce((prev, curr) => {
      prev[curr] = imports[curr];
      return prev;
    }, {});
  return directives && directives?.length > 0 ? filteredComponents : imports;
};
