export const componentMap = (directives) => {
  const imports = {
    admonition: import('../../../../src/components/Admonition'),
    banner: import('../../../../src/components/Banner/Banner'),
    blockquote: import('../../../../src/components/BlockQuote'),
    button: import('../../../../src/components/Button'),
    card: import('../../../../src/components/Card'),
    'card-group': import('../../../../src/components/Card/CardGroup'),
    chapter: import('../../../../src/components/Chapters/Chapter'),
    chapters: import('../../../../src/components/Chapters'),
    chatbot: import('../../../../src/components/ChatbotUi'),
    code: import('../../../../src/components/Code/Code'),
    'io-code-block': import('../../../../src/components/Code/CodeIO'),
    cond: import('../../../../src/components/Cond'),
    container: import('../../../../src/components/Container'),
    cta: import('../../../../src/components/CTA'),
    'cta-banner': import('../../../../src/components/Banner/CTABanner'),
    definitionList: import('../../../../src/components/DefinitionList'),
    definitionListItem: import('../../../../src/components/DefinitionList/DefinitionListItem'),
    deprecated: import('../../../../src/components/VersionModified'),
    'deprecated-version-selector': import('../../../../src/components/DeprecatedVersionSelector'),
    describe: import('../../../../src/components/Describe'),
    emphasis: import('../../../../src/components/Emphasis'),
    extract: import('../../../../src/components/Extract'),
    field: import('../../../../src/components/FieldList/Field'),
    field_list: import('../../../../src/components/FieldList'),
    figure: import('../../../../src/components/Figure'),
    footnote: import('../../../../src/components/Footnote'),
    footnote_reference: import('../../../../src/components/Footnote/FootnoteReference'),
    glossary: import('../../../../src/components/Glossary'),
    'guide-next': import('../../../../src/components/GuideNext'),
    heading: import('../../../../src/components/Heading'),
    hlist: import('../../../../src/components/HorizontalList'),
    image: import('../../../../src/components/Image'),
    include: import('../../../../src/components/Include'),
    introduction: import('../../../../src/components/Introduction'),
    kicker: import('../../../../src/components/Kicker'),
    'landing:explore': import('../../../../src/components/Landing/Explore'),
    'landing:more-ways': import('../../../../src/components/Landing/MoreWays'),
    'landing:client-libraries': import('../../../../src/components/StandaloneHeader'),
    'landing:introduction': import('../../../../src/components/LandingIntro'),
    'landing:product': import('../../../../src/components/Products/ProductItem'),
    'landing:products': import('../../../../src/components/Products'),
    line: import('../../../../src/components/LineBlock/Line'),
    line_block: import('../../../../src/components/LineBlock'),
    list: import('../../../../src/components/List'),
    listItem: import('../../../../src/components/List/ListItem'),
    'list-table': import('../../../../src/components/ListTable'),
    literal: import('../../../../src/components/Literal'),
    literal_block: import('../../../../src/components/LiteralBlock'),
    literalinclude: import('../../../../src/components/LiteralInclude'),
    only: import('../../../../src/components/Cond'),
    'openapi-changelog': import('../../../../src/components/OpenAPIChangelog'),
    paragraph: import('../../../../src/components/Paragraph'),
    procedure: import('../../../../src/components/Procedure'),
    ref_role: import('../../../../src/components/RefRole'),
    reference: import('../../../../src/components/Reference'),
    release_specification: import('../../../../src/components/ReleaseSpecification'),
    root: import('../../../../src/components/Root'),
    rubric: import('../../../../src/components/Rubric'),
    'search-results': import('../../../../src/components/SearchResults'),
    section: import('../../../../src/components/Section'),
    sharedinclude: import('../../../../src/components/Include'),
    strong: import('../../../../src/components/Strong'),
    substitution_reference: import('../../../../src/components/SubstitutionReference'),
    tabs: import('../../../../src/components/Tabs'),
    target: import('../../../../src/components/Target'),
    text: import('../../../../src/components/Text'),
    time: import('../../../../src/components/Time'),
    title_reference: import('../../../../src/components/TitleReference'),
    topic: import('../../../../src/components/Topic'),
    transition: import('../../../../src/components/Transition'),
    versionadded: import('../../../../src/components/VersionModified'),
    versionchanged: import('../../../../src/components/VersionModified'),
  };

  const filteredComponents = directives
    .filter((key) => key in imports)
    .reduce((acc, key) => (acc[key] = imports[key]), {});
  return directives && directives.length ? filteredComponents : imports;
};
