from .events import FileSystemEventHandler


class Observer:
    def schedule(self, handler: FileSystemEventHandler, path: str, recursive: bool=True) -> None: ...
    def start(self) -> None: ...
    def join(self) -> None: ...
