from typing import Any, Dict


class Endpoint:
    def __init__(self, server: Any, cb: Any) -> None: ...
    def notify(self, method: str, params: Dict[str, object]) -> None: ...
    def consume(self, data: object) -> None: ...
    def shutdown(self) -> None: ...
