from typing import BinaryIO, Callable


class JsonRpcStreamReader:
    def __init__(self, rfile: BinaryIO) -> None: ...
    def close(self) -> None: ...
    def listen(self, message_consumer: Callable[[object], None]) -> None: ...


class JsonRpcStreamWriter:
    def __init__(self, wfile: BinaryIO) -> None: ...
    def close(self) -> None: ...
    def write(self, message: object) -> None: ...
