import docutils
import docutils.nodes
import docutils.frontend


def new_document(path: str, settings: docutils.frontend.Values) -> docutils.nodes.document: ...


class SystemMessage(docutils.ApplicationError): ...


class Reporter:
    DEBUG_LEVEL: int = ...
    INFO_LEVEL: int = ...
    WARNING_LEVEL: int = ...
    ERROR_LEVEL: int = ...
    SEVERE_LEVEL: int = ...

    def warning(self, *args: object, **kwargs: object) -> docutils.nodes.system_message: ...
    def error(self, *args: object, **kwargs: object) -> docutils.nodes.system_message: ...
