on:
  push:
    branches:
    - DOP-4247-build-artifacts
name: Cloud-docs Lighthouse
jobs: 
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #----------------------------------------------
      #  -----  install node  -----
      #----------------------------------------------
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      #----------------------------------------------
      #  -----  install python  -----
      #----------------------------------------------
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      # - name: Ssh
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.GITHUB_TOKEN }}
      # - name: Clone
      #   run: |
      #     git clone https://github.com/10gen/cloud-docs.git
      # #----------------------------------------------
      # #  -----  Run custom Github Action  -----
      # #----------------------------------------------
      # - name: Cloud Docs Build
      #   uses: mongodb/docs-worker-actions/build-cloud-docs@DOP-4247-build-artifact
      #   env: 
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
