on:
  push:
    branches:
    - DOP-4247-build-artifacts
name: Initial Feature Branch Deploy
jobs: 
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Get Webhook URL 
        uses: mongodb/docs-worker-actions/build-artifact@DOP-4247-build-artifact
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
